---
title: "CV"
author: "Luke W. Johnston"
name: Luke
surname: Johnston
position: Postdoctoral researcher
address: Aarhus, Denmark
date: "`r cv::today_timestamp()`"
# profilepic: A local file path to an image
www: lukewjohnston.com
email: lwjohnst@gmail.com
#twitter: lwjohnst
github: lwjohnst86
aboutme: I am a diabetes epidemiologist, R user and developer, teacher of modern data science and analysis skills, and open science advocate.
headcolor: "324ea8"
docname: "curriculum vitae"
csl: vancouver.csl
output:
    pagedown::html_resume:
        # set it to true for a self-contained HTML page 
        # but it'll take longer to render
        keep_md: yes
        self_contained: false
    vitae::awesomecv: 
        keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    warning = FALSE,
    message = FALSE,
    results = "asis",
    comment = ""
)
# library(cv)
library(here)
devtools::load_all()
library(tidyverse)
library(RefManageR)
RefManageR::BibOptions(
    bib.style = "authoryear",
    first.inits = TRUE,
    style = "markdown",
    max.names = Inf,
    sorting = "ydnt"
    # no.print.fields = NULL
)
cv_data <- read_cv_items() 
bib_items <- read_bib_items() 
rpkgs <- cv::rpackages
```

## `r fa("graduation-cap")` Education

```{r list-education}
list_education()
```

## `r fa("university")` Affiliations

```{r list-affiliations}
list_affiliations(cv_data)
```

## `r fa("book-open")` Publications

```{r list-articles}
list_publications(bib_items, "Journal articles")
```

## `r fa("comment-dots")` Presentations

```{r list-presentations}
list_publications(bib_items, "presentations")
```

## `r fa("box-open")` R packages

```{r list-r-packages}
list_rpackages(rpkgs) 
```

## `r fa("chalkboard-teacher")` Teaching 

```{r list-teaching}
list_teaching(cv_data)
```

## `r fa("user-friends")` Supervision

```{r list-supervision}
list_supervision(cv_data)
```

## `r fa("book-reader")` Curriculum development

```{r list-curriculum-archived}
list_publications(bib_items, "Curriculum development")
```

### Other Development

```{r list-curriculum}
list_curriculum_development(cv_data)
```

## `r fa("trophy")` Awards

```{r list-awards}
list_awards(cv_data)
```

## `r fa("briefcase")` Employment

```{r list-employment}
list_employment(cv_data)
```
