---
date: "`r cv::today_timestamp()`"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(cv)
```

# Luke William Johnston

**Address**: Vesterport 3, 2.1, 8000 Aarhus, Denmark

Diabetes epidemiologist, R user and developer, teacher of modern data science
and analysis skills, and open science and reproducibility advocate. 
*Only showing items since 2018. For full CV, see [cv.lukewjohnston.com](https://cv.lukewjohnston.com/).*

<!--
Personal data: Name, address, etc.
Education (for academic degrees, list the date and year of obtaining the degree).
Current and most recent positions held.
Other scientific qualifications and scientific focus areas.
Experience with supervision/mentoring, teaching or planning of courses/conferences or the like.
International relations, interdisciplinary or cross-sectoral collaborations.
Academic awards and honours.
Invited oral presentations at international conferences.
Public dissemination of the candidate’s research and results thereof, i.e. on social media, in the press or in the public in general.
External funding obtained.
List of publications (only already published or accepted publications should be included), including H-index.


## Skills

- Languages: English (fluent), Spanish (competent)
- Programming: Fluent in R, LaTeX, HTML, CSS, Bash, Git; familiar with 
SAS, Python.
- Statistical techniques: Basic (t-test, ANOVA, correlation), regression
modeling (linear, logistic), mixed effect modeling, generalized estimating
equations, principal component analysis, partial least squares regression, cross
validation, cluster analysis (hierarchical, k-means), information criterion
(AIC, QIC), bootstrapping, factor analysis.
-->

```{r insert-cv, child="cv.Rmd"}
```
